name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'google-sdk/467.0.0-alpine/*'

jobs:
  build-push-google-sdk-467:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push google-sdk 467.0.0 alpine
        uses: docker/build-push-action@v5
        with:
          file: ./google-sdk/467.0.0-alpine/Dockerfile
          context: ./google-sdk/467.0.0-alpine/
          push: true
          tags: imageszh/google-sdk:latest
